package com.oregontrail.engine

/**
 * Runs the [TestPilot] across many seeded games and aggregates the results.
 * Used by the balance assertions and by the `balanceReport` Gradle task.
 */
object BalanceHarness {

    data class Row(
        val occ: Occupation, val diff: Difficulty, val n: Int,
        val arrivals: Int, val avgDays: Int, val avgSurvivors: Double, val avgScore: Int,
        val avgFood: Int, val avgAmmo: Int, val avgCash: Int, val avgOxen: Int,
        val avgClothing: Int, val avgHunts: Double, val avgRests: Double,
        val deathCauses: Map<String, Int>
    ) {
        val rate: Double get() = arrivals.toDouble() / n
    }

    fun measure(occ: Occupation, diff: Difficulty, n: Int): Row {
        var arrivals = 0
        var days = 0
        var survivors = 0.0
        var score = 0
        var food = 0
        var ammo = 0
        var cash = 0
        var oxen = 0
        var clothes = 0
        var hunts = 0.0
        var rests = 0.0
        val causes = HashMap<String, Int>()
        for (s in 1..n) {
            val o = TestPilot(s * 31L + diff.ordinal, occ, diff).play()
            if (o.arrived) { arrivals++; score += o.score }
            days += o.days
            survivors += o.survived
            food += o.food; ammo += o.ammo; cash += o.cash; oxen += o.oxen; clothes += o.clothing
            hunts += o.hunts; rests += o.rests
            for (c in o.deathCauses) causes[c] = (causes[c] ?: 0) + 1
        }
        return Row(
            occ, diff, n, arrivals, days / n, survivors / n,
            if (arrivals == 0) 0 else score / arrivals,
            food / n, ammo / n, cash / n, oxen / n, clothes / n,
            hunts / n, rests / n, causes
        )
    }

    fun all(n: Int): List<Row> =
        Difficulty.entries.flatMap { d -> Occupation.entries.map { o -> measure(o, d, n) } }

    /** A Markdown report suitable for committing or reading in a terminal. */
    fun markdown(rows: List<Row>): String {
        val sb = StringBuilder()
        sb.append("# Oregon Trail - balance report\n\n")
        sb.append("Generated by `./gradlew balanceReport` using the headless ")
        sb.append("[TestPilot] bot over ${rows.firstOrNull()?.n ?: 0} games per cell. ")
        sb.append("The bot plays conservatively (buys a full outfit, hunts and rations ")
        sb.append("sensibly, rests when hurt), so these are close to best-case numbers.\n\n")
        sb.append("> Easy should lose almost no one. Normal should usually arrive, but ")
        sb.append("with losses. Hard should be a gamble. The Farmer (least money) should ")
        sb.append("be the hardest crossing yet score the most.\n\n")
        sb.append("| Occupation | Difficulty | Arrived | Alive | Days | Score | Food | Ammo | Cash | Oxen | Hunts | Rests |\n")
        sb.append("|---|---|---|---|---|---|---|---|---|---|---|---|\n")
        for (r in rows) {
            sb.append(
                "| %s | %s | %d%% | %.2f | %d | %d | %d | %d | $%d | %d | %.1f | %.1f |\n".format(
                    r.occ.displayName, r.diff.displayName, (r.rate * 100).toInt(),
                    r.avgSurvivors, r.avgDays, r.avgScore, r.avgFood, r.avgAmmo,
                    r.avgCash, r.avgOxen, r.avgHunts, r.avgRests
                )
            )
        }
        val causes = HashMap<String, Int>()
        for (r in rows) for ((c, v) in r.deathCauses) causes[c] = (causes[c] ?: 0) + v
        if (causes.isNotEmpty()) {
            sb.append("\n### Causes of death (all runs)\n\n| Cause | Deaths |\n|---|---|\n")
            causes.entries.sortedByDescending { it.value }.take(10)
                .forEach { (c, v) -> sb.append("| $c | $v |\n") }
        }
        return sb.toString()
    }
}
